config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
]

menu/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('<str:title>/', views.menu, name='menu'),
]

menu/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=55)
    submenu = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title

menu/views.py
from django.shortcuts import render

from .models import Category


def index(request):
    queryset = Category.objects.filter(submenu=None)

    data = {
        'data': queryset
    }
    return render(request, 'menu/index.html', data)


def menu(request, title):
    queryset = Category.objects.filter(title=title)

    data = {
        'data': queryset
    }
    return render(request, 'menu/index.html', data)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% block 'title' %}{% endblock %}


</head>
<body>
    <a href="{% url 'home' %}"> Home </a>
    <br><br>

    {% block 'content' %}
    {% endblock %}

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/blocks/render_tree_menu.html
{% for subcategory in category.category_set.all %}
    <ul class="nested">
        <li>
            <span class="caret"><a href="{% url 'menu' subcategory.title %}">{{ subcategory.title }}</a></span>
            {% include 'blocks/render_tree_menu.html' with category=subcategory %}
        </li>
    </ul>
{% endfor %}

templates/menu/index.html
{% extends 'base.html' %}

{% block 'title' %} <title>Menu</title> {% endblock %}

{% block 'content' %}

    <ul id="myUL">
        <li><span class="caret">Категории</span>
            <ul class="nested">
              {% for category in data %}
                 <li>
                    <span class="caret">
                        <a href="{% url 'menu' category.title %}">{{ category.title }}</a>
                    </span>

                    {% include 'blocks/render_tree_menu.html' with category=category %}
                 </li>
              {% endfor %}
            </ul>
        </li>
    </ul>

{% endblock %}